import {
  RESEARCH_TREE,
  INITIAL_OPEN,
  INITIAL_ACTIVE,
  HYPOTHESES,
  EXPERIMENTS,
  DATASETS,
  PAPERS,
  PROTOCOLS,
  AGENTS,
  INSIGHTS,
  TEAM,
} from "../data";
import type { WorkspaceBundle } from "../workspace-model";

export const ireDemoBundle: WorkspaceBundle = {
  tree: RESEARCH_TREE,
  initialOpen: INITIAL_OPEN,
  initialActive: INITIAL_ACTIVE,
  hypotheses: HYPOTHESES,
  experiments: EXPERIMENTS,
  datasets: DATASETS,
  papers: PAPERS,
  protocols: PROTOCOLS,
  agents: AGENTS,
  insights: INSIGHTS,
  team: TEAM,
  chrome: {
    projectDropdownTitle: "EGFR Inhibitor Discovery",
    projectVersionSuffix: " · v3",
    branchCrumbs: "hypothesis/H-001",
    runningExperimentsDisplay: "2 running",
    agentsDisplay: "4 agents online",
    anomaliesDisplay: "1 anomaly",
    statusHypothesisRef: "hypothesis/H-001",
    statusVersionSigned: "v12 · signed",
    statusAnomalySummary: "2 anomalies",
    statusFairAvg: "FAIR avg 94",
    statusExperimentProgress: "EXP-002 step 4/8",
    statusProvenance: "provenance ✓",
    statusAgentsDigest: "4 agents · 1 digest",
    statusComputeJobs: "2 jobs · HPC",
    experimentActivityBadge: 2,
    literatureActivityBadge: 2,
  },
};
